### ISSUE TITLE
[Enhancement] Change in Folder Structure

### ISSUE THREAD

**Issue by Kris0011** [csiddu/Frontend-Treasure#16]
In this folder structure you are statically selecting the components cards by giving them link and putting them into the component.html .
But If components list increases in future then it would be difficult and also will not look good to add every card in the component.html .
Rather than doing this we can have one file for storing the information for components like "components.json" . This file will contain the Title , Author , Link the the component's code from the components directory and also can add image URL . By doing this we can fetch the data by running the script and add all component to the components.html page. This method is efficient way to fetch all the components . Now if someone adds new component then we just need to modify the components.json file and add details of it , it will be automatically added to the components.html page .

**Comment by Rushi0508** [comment]
Okay, I am assigning the issue to you. Also make sure to edit the readme and add the necessary instructions for uploading new components.
