### ISSUE TITLE
[Hactoberfest, New Feature] Reusable Slider Component with infinite autoplay using React.

### ISSUE THREAD

**Issue by kevintamakuwala** [csiddu/Frontend-Treasure#23]
I would like to commit the following changes:

- Created a React sub-project in the components directory where all the react components can be used to the HTML project. This has also enabled me to resolve the **BUG** in script.js file i.e. the url has been relatively rendered which works fine only for HTML components. I have made it as absolute path for the browser, by editing JSON file.
- Created a re-usable slider using React libraries with all the possible configurations, wherein a user can enable/disable autoplay by just commenting out one line of code. Autoplay will start only when component is present on the Viewport, This can also be achieved by commenting out a piece of code.

Please, assign this issue to me.

**Comment by Rushi0508** [comment]
@kevintamakuwala I am assigning the issue to you. Please note that currently there is no React configuration in repo, so make sure that everything works correctly.
